In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

# Reading in the Data

In [2]:
data_13 = pd.read_excel("MATERNITY_MEM_2013.xlsx")
data_14 = pd.read_excel("MATERNITY_MEM_2014.xlsx")
data_15 = pd.read_excel("MATERNITY_MEM_2015.xlsx")
data_16 = pd.read_excel("MATERNITY_MEM_2016.xlsx")
data_17 = pd.read_excel("MATERNITY_MEM_2017.xlsx")
data_18 = pd.read_excel("MATERNITY_MEM_2018.xlsx")
data_19 = pd.read_excel("MATERNITY_MEM_2019.xlsx")

In [3]:
scheme_B=pd.read_excel("B_MATERNITY_EXPOSURE.xlsx")
scheme_C=pd.read_excel("C_MATERNITY_MEM_EXPOSURE.xlsx")

# Merging the Data

In [4]:
scheme_A_no_13_or_14=pd.concat(objs=[data_15,data_16,data_17,data_18,data_19])

In [5]:
scheme_A_no_13_or_14.head(3)

year GENDER  age_at_treatment  REGION_DESCR     dpm_ind  exposure
0  2015      F                12  EASTERN CAPE       Group      5800
1  2015      F                12  EASTERN CAPE  Individual       424
2  2015      F                12    FREE STATE       Group      2717

# Cleaning the Headings

In [6]:
data_13.columns=data_13.columns.str.title()
data_14.columns=data_14.columns.str.title()
scheme_A_no_13_or_14.columns=scheme_A_no_13_or_14.columns.str.title()
scheme_B.columns=scheme_B.columns.str.title()
scheme_C.columns=scheme_C.columns.str.title()

# Removing the Rows Where the Region is Outside of South Africa

In [7]:
scheme_A_no_13_or_14.replace(to_replace="KWAZULU-NATAL",value="KWAZULU NATAL",inplace=True)
scheme_A_no_13_or_14.replace(to_replace="NORTHWEST PROVINCE",value="NORTH WEST",inplace=True)

In [8]:
scheme_A_no_13_or_14["Region_Descr"].unique().tolist()

['EASTERN CAPE',
 'FREE STATE',
 'GAUTENG',
 'KWAZULU NATAL',
 'LESOTHO',
 'LIMPOPO',
 'MPUMALANGA',
 'NAMIBIA',
 'NORTH WEST',
 'NORTHERN CAPE',
 'SWAZILAND',
 'Unknown',
 'WESTERN CAPE',
 'ZIMBABWE',
 'ANGOLA',
 'BOTSWANA',
 'BRAZIL',
 'NEW ZEALAND',
 'ZAMBIA',
 'UGANDA']

In [9]:
req1=scheme_A_no_13_or_14["Region_Descr"]=="NORTHERN CAPE"
req2=scheme_A_no_13_or_14["Region_Descr"]=="KWAZULU NATAL"
req3=scheme_A_no_13_or_14["Region_Descr"]=="EASTERN CAPE"
req4=scheme_A_no_13_or_14["Region_Descr"]=="GAUTENG"
req5=scheme_A_no_13_or_14["Region_Descr"]=="LIMPOPO"
req6=scheme_A_no_13_or_14["Region_Descr"]=="FREE STATE"
req7=scheme_A_no_13_or_14["Region_Descr"]=="NORTH WEST"
req8=scheme_A_no_13_or_14["Region_Descr"]=="MPUMALANGA"
req9=scheme_A_no_13_or_14["Region_Descr"]=="WESTERN CAPE"
req10=scheme_A_no_13_or_14["Region_Descr"]=="nan"

In [10]:
scheme_A_no_13_or_14=scheme_A_no_13_or_14[req1|req2|req3|req4|req5|req6|req7|req8|req9|req10]

In [11]:
scheme_A_no_13_or_14["Region_Descr"].unique().tolist()

['EASTERN CAPE',
 'FREE STATE',
 'GAUTENG',
 'KWAZULU NATAL',
 'LIMPOPO',
 'MPUMALANGA',
 'NORTH WEST',
 'NORTHERN CAPE',
 'WESTERN CAPE']

In [12]:
scheme_A=pd.concat([scheme_A_no_13_or_14,data_13,data_14])

In [13]:
scheme_A

Year Gender  Age_At_Treatment  Region_Descr     Dpm_Ind  Exposure  \
0    2015      F                12  EASTERN CAPE       Group      5800   
1    2015      F                12  EASTERN CAPE  Individual       424   
2    2015      F                12    FREE STATE       Group      2717   
3    2015      F                12    FREE STATE  Individual       350   
4    2015      F                12       GAUTENG       Group     18888   
..    ...    ...               ...           ...         ...       ...   
681  2014      F                60           NaN  Individual       396   
682  2014      F                60           NaN       Group      2610   
683  2014      F                60           NaN  Individual      1897   
684  2014      F                60           NaN       Group     16691   
685  2014      F                60           NaN  Individual      6707   

               Plan_Name  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
..                   ...  
681  BonEssential Option  
682       PRIMARY OPTION  
683       PRIMARY OPTION  
684      STANDARD OPTION  
685      STANDARD OPTION  

[6273 rows x 7 columns]

# Breaking Up the Data into Years

In [14]:
scheme_A["Year"].unique()

array([2015, 2016, 2017, 2018, 2019, 2013, 2014])

In [15]:
scheme_A_13=scheme_A[scheme_A["Year"]==2013]
scheme_A_14=scheme_A[scheme_A["Year"]==2014]
scheme_A_15=scheme_A[scheme_A["Year"]==2015]
scheme_A_16=scheme_A[scheme_A["Year"]==2016]
scheme_A_17=scheme_A[scheme_A["Year"]==2017]
scheme_A_18=scheme_A[scheme_A["Year"]==2018]
scheme_A_19=scheme_A[scheme_A["Year"]==2019]

In [16]:
scheme_B["Year"].unique()

array([2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [17]:
scheme_B_13=scheme_B[scheme_B["Year"]==2013]
scheme_B_14=scheme_B[scheme_B["Year"]==2014]
scheme_B_15=scheme_B[scheme_B["Year"]==2015]
scheme_B_16=scheme_B[scheme_B["Year"]==2016]
scheme_B_17=scheme_B[scheme_B["Year"]==2017]
scheme_B_18=scheme_B[scheme_B["Year"]==2018]
scheme_B_19=scheme_B[scheme_B["Year"]==2019]
scheme_B_20=scheme_B[scheme_B["Year"]==2020]

In [18]:
scheme_C["Year"].unique()

array([2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [19]:
scheme_C_13=scheme_C[scheme_C["Year"]==2013]
scheme_C_14=scheme_C[scheme_C["Year"]==2014]
scheme_C_15=scheme_C[scheme_C["Year"]==2015]
scheme_C_16=scheme_C[scheme_C["Year"]==2016]
scheme_C_17=scheme_C[scheme_C["Year"]==2017]
scheme_C_18=scheme_C[scheme_C["Year"]==2018]
scheme_C_19=scheme_C[scheme_C["Year"]==2019]
scheme_C_20=scheme_C[scheme_C["Year"]==2020]

# Calculating Number of Female Members of Childbearing Age per Year for Each Scheme

Scheme A

In [20]:
{
    'Number of Female Members in 2013':round((scheme_A_13["Exposure"].sum())/12,2),
    'Number of Female Members in 2014':round((scheme_A_14["Exposure"].sum())/12,2),
    'Number of Female Members in 2015':round((scheme_A_15["Exposure"].sum())/12,2),
    'Number of Female Members in 2016':round((scheme_A_16["Exposure"].sum())/12,2),
    'Number of Female Members in 2017':round((scheme_A_17["Exposure"].sum())/12,2),
    'Number of Female Members in 2018':round((scheme_A_18["Exposure"].sum())/12,2),
    'Number of Female Members in 2019':round((scheme_A_19["Exposure"].sum())/12,2),
}

{'Number of Female Members in 2013': 230565.5,
 'Number of Female Members in 2014': 230312.08,
 'Number of Female Members in 2015': 228383.42,
 'Number of Female Members in 2016': 226262.5,
 'Number of Female Members in 2017': 252395.25,
 'Number of Female Members in 2018': 245989.42,
 'Number of Female Members in 2019': 248636.5}

In [21]:
print(f'Average Number of Members per Year : {round(((scheme_A_13["Exposure"].sum())/12+(scheme_A_14["Exposure"].sum())/12+(scheme_A_15["Exposure"].sum())/12+(scheme_A_16["Exposure"].sum())/12+(scheme_A_17["Exposure"].sum())/12+(scheme_A_18["Exposure"].sum())/12+(scheme_A_19["Exposure"].sum())/12)/7,2)}')

Average Number of Members per Year : 237506.38


Scheme B

In [22]:
{
    'Number of Female Members in 2013':round((scheme_B_13["Exposure"].sum())/12,2),
    'Number of Female Members in 2014':round((scheme_B_14["Exposure"].sum())/12,2),
    'Number of Female Members in 2015':round((scheme_B_15["Exposure"].sum())/12,2),
    'Number of Female Members in 2016':round((scheme_B_16["Exposure"].sum())/12,2),
    'Number of Female Members in 2017':round((scheme_B_17["Exposure"].sum())/12,2),
    'Number of Female Members in 2018':round((scheme_B_18["Exposure"].sum())/12,2),
    'Number of Female Members in 2019':round((scheme_B_19["Exposure"].sum())/12,2),
}

{'Number of Female Members in 2013': 52973.25,
 'Number of Female Members in 2014': 52719.67,
 'Number of Female Members in 2015': 50461.25,
 'Number of Female Members in 2016': 49776.92,
 'Number of Female Members in 2017': 48847.17,
 'Number of Female Members in 2018': 48259.25,
 'Number of Female Members in 2019': 48258.33}

In [23]:
print(f'Average Number of Members per Year : {round(((scheme_B_13["Exposure"].sum())/12+(scheme_B_14["Exposure"].sum())/12+(scheme_B_15["Exposure"].sum())/12+(scheme_B_16["Exposure"].sum())/12+(scheme_B_17["Exposure"].sum())/12+(scheme_B_18["Exposure"].sum())/12+(scheme_B_19["Exposure"].sum())/12)/7,2)}')

Average Number of Members per Year : 50185.12


Scheme C

In [24]:
{
    'Number of Female Members in 2013':round((scheme_C_13["Exposure"].sum())/12,2),
    'Number of Female Members in 2014':round((scheme_C_14["Exposure"].sum())/12,2),
    'Number of Female Members in 2015':round((scheme_C_15["Exposure"].sum())/12,2),
    'Number of Female Members in 2016':round((scheme_C_16["Exposure"].sum())/12,2),
    'Number of Female Members in 2017':round((scheme_C_17["Exposure"].sum())/12,2),
    'Number of Female Members in 2018':round((scheme_C_18["Exposure"].sum())/12,2),
    'Number of Female Members in 2019':round((scheme_C_19["Exposure"].sum())/12,2),
}

{'Number of Female Members in 2013': 26125.83,
 'Number of Female Members in 2014': 26081.67,
 'Number of Female Members in 2015': 24985.42,
 'Number of Female Members in 2016': 24777.0,
 'Number of Female Members in 2017': 25216.5,
 'Number of Female Members in 2018': 25416.75,
 'Number of Female Members in 2019': 25443.25}

In [25]:
print(f'Average Number of Members per Year : {round(((scheme_C_13["Exposure"].sum())/12+(scheme_C_14["Exposure"].sum())/12+(scheme_C_15["Exposure"].sum())/12+(scheme_C_16["Exposure"].sum())/12+(scheme_C_17["Exposure"].sum())/12+(scheme_C_18["Exposure"].sum())/12+(scheme_C_19["Exposure"].sum())/12)/7,2)}')

Average Number of Members per Year : 25435.2


# Calculating Number of Members per Year for All Schemes

In [26]:
data=pd.concat(objs=[scheme_A,scheme_B,scheme_C])

In [27]:
data_13=data[data["Year"]==2013]
data_14=data[data["Year"]==2014]
data_15=data[data["Year"]==2015]
data_16=data[data["Year"]==2016]
data_17=data[data["Year"]==2017]
data_18=data[data["Year"]==2018]
data_19=data[data["Year"]==2019]

In [28]:
{
    'Number of Female Members in 2013':round((data_13["Exposure"].sum())/12,2),
    'Number of Female Members in 2014':round((data_14["Exposure"].sum())/12,2),
    'Number of Female Members in 2015':round((data_15["Exposure"].sum())/12,2),
    'Number of Female Members in 2016':round((data_16["Exposure"].sum())/12,2),
    'Number of Female Members in 2017':round((data_17["Exposure"].sum())/12,2),
    'Number of Female Members in 2018':round((data_18["Exposure"].sum())/12,2),
    'Number of Female Members in 2019':round((data_19["Exposure"].sum())/12,2),
}

{'Number of Female Members in 2013': 309664.58,
 'Number of Female Members in 2014': 309113.42,
 'Number of Female Members in 2015': 303830.08,
 'Number of Female Members in 2016': 300816.42,
 'Number of Female Members in 2017': 326458.92,
 'Number of Female Members in 2018': 319665.42,
 'Number of Female Members in 2019': 322338.08}

In [29]:
print(f'Average Number of Members per Year : {round(((data_13["Exposure"].sum())/12+(data_14["Exposure"].sum())/12+(data_15["Exposure"].sum())/12+(data_16["Exposure"].sum())/12+(data_17["Exposure"].sum())/12+(data_18["Exposure"].sum())/12+(data_19["Exposure"].sum())/12)/7,2)}')


Average Number of Members per Year : 313126.7
